### ISSUE TITLE
GitHub workflow to build Docker image

### ISSUE THREAD

**Issue by amottier** [fasten-project/debian-scraper#1]
I think it would be nice to add the required GitHub workflow to build the Debian Scraper Docker image when a new tagged is created on the `master` branch.

**Comment by gdrosos** [comment]
Thanks Antoine(@amottier), resolved on 1053a76.

**Comment by amottier** [comment]
Thanks a lot @gdrosos :+1:  Do you think it would be ok to tag a `v0.0.1` on `debian-scraper` project?

**Comment by amottier** [comment]
Thanks a lot @gdrosos :+1:  Do you think it would be ok to tag a `v0.0.1` on `debian-scraper` project?

**Comment by amottier** [comment]
@gdrosos for info I update a little bit the GitHub workflow to be triggered also on new tag (tag name matching can be a little bit more restrictive I guess but I was having issue with the syntax).
And I tagged version `v0.0.1` that can be used when addressing https://github.com/fasten-project/k8s-deployments/issues/72
